version: "3.3"

services:
  neo.user:
    image: neo.user
    container_name: "neo.user"
    restart: always
    ports:
      - 8080:8080
    volumes:
      - "./target/neo.user.jar:/app.jar"
    command: ['java', '-jar', '/app.jar']
    networks:  
      - local-dev2
networks:
  local-dev2:
    external: false
    name: local-dev2