version: '3'
services:
    redis:
        container_name: redis
        hostname: redislocal
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"
        command: ["redis-server", "--bind", "redis", "--port", "6379"]
        networks:  
            - local-dev2
        
networks:
  local-dev2:
    external: false
    name: local-dev2