version: '3'
services:
    redis:
        container_name: redis
        hostname: redislocal
        image: redis:latest
        ports:
            - "6379:6379"
        command: ["redis-server", "--bind", "redis", "--port", "6379"]
